# Generated by Django 4.2.3 on 2023-08-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='valor_mes',
            new_name='total',
        ),
    ]
